// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: x0 => x0.createRange(),
      _1282: (x0,x1) => x0.selectNode(x1),
      _1283: x0 => x0.getSelection(),
      _1284: x0 => x0.removeAllRanges(),
      _1285: (x0,x1) => x0.addRange(x1),
      _1286: (x0,x1) => x0.createElement(x1),
      _1287: (x0,x1) => x0.append(x1),
      _1288: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1289: (x0,x1) => x0.add(x1),
      _1290: x0 => x0.preventDefault(),
      _1291: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1291(f,arguments.length,x0) }),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: () => globalThis.window.navigator.userAgent,
      _1295: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1296: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1297: (x0,x1) => x0.createElement(x1),
      _1304: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1305: (x0,x1) => x0.canShare(x1),
      _1306: (x0,x1) => x0.share(x1),
      _1307: x0 => ({url: x0}),
      _1308: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1309: (x0,x1) => ({files: x0,text: x1}),
      _1310: (x0,x1) => ({files: x0,title: x1}),
      _1311: x0 => ({files: x0}),
      _1312: (x0,x1) => ({title: x0,text: x1}),
      _1313: x0 => ({text: x0}),
      _1314: x0 => x0.click(),
      _1315: x0 => x0.remove(),
      _1316: () => ({}),
      _1317: (x0,x1,x2) => new File(x0,x1,x2),
      _1318: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1318(f,arguments.length,x0) }),
      _1319: (x0,x1,x2) => globalThis.jsConnect(x0,x1,x2),
      _1320: (x0,x1) => globalThis.jsSend(x0,x1),
      _1321: x0 => globalThis.jsDisconnect(x0),
      _1322: x0 => x0.read(),
      _1323: (x0,x1) => x0.getType(x1),
      _1324: x0 => ({type: x0}),
      _1325: (x0,x1) => new Blob(x0,x1),
      _1326: x0 => new ClipboardItem(x0),
      _1327: (x0,x1) => x0.write(x1),
      _1331: () => new FileReader(),
      _1333: x0 => x0.arrayBuffer(),
      _1339: x0 => x0.decode(),
      _1340: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1341: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1342: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1342(f,arguments.length,x0) }),
      _1343: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1343(f,arguments.length,x0) }),
      _1344: x0 => x0.send(),
      _1345: () => new XMLHttpRequest(),
      _1346: () => new AudioContext(),
      _1347: (x0,x1) => x0.createMediaElementSource(x1),
      _1348: x0 => x0.createGain(),
      _1349: x0 => x0.createStereoPanner(),
      _1350: (x0,x1) => x0.connect(x1),
      _1351: x0 => x0.load(),
      _1352: x0 => x0.disconnect(),
      _1353: x0 => x0.resume(),
      _1354: x0 => x0.play(),
      _1355: x0 => x0.pause(),
      _1356: x0 => x0.close(),
      _1357: (x0,x1) => x0.getItem(x1),
      _1358: (x0,x1) => x0.removeItem(x1),
      _1359: (x0,x1,x2) => x0.setItem(x1,x2),
      _1360: x0 => ({frequency: x0}),
      _1361: x0 => new Accelerometer(x0),
      _1362: x0 => x0.start(),
      _1363: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1363(f,arguments.length,x0) }),
      _1364: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1364(f,arguments.length,x0) }),
      _1365: x0 => new Gyroscope(x0),
      _1366: x0 => x0.start(),
      _1367: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1367(f,arguments.length,x0) }),
      _1368: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1368(f,arguments.length,x0) }),
      _1369: x0 => new LinearAccelerationSensor(x0),
      _1370: x0 => x0.start(),
      _1371: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1371(f,arguments.length,x0) }),
      _1372: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1372(f,arguments.length,x0) }),
      _1373: x0 => new Magnetometer(x0),
      _1374: x0 => x0.start(),
      _1375: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1375(f,arguments.length,x0) }),
      _1376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1376(f,arguments.length,x0) }),
      _1377: (x0,x1) => x0.querySelector(x1),
      _1378: x0 => globalThis.URL.createObjectURL(x0),
      _1379: (x0,x1) => x0.item(x1),
      _1380: (x0,x1) => x0.readAsDataURL(x1),
      _1381: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1382: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1382(f,arguments.length,x0) }),
      _1383: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1384: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1384(f,arguments.length,x0) }),
      _1385: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1386: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1386(f,arguments.length,x0) }),
      _1387: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1387(f,arguments.length,x0) }),
      _1388: (x0,x1) => x0.removeChild(x1),
      _1389: x0 => new Blob(x0),
      _1390: x0 => globalThis.URL.revokeObjectURL(x0),
      _1391: (x0,x1,x2) => x0.slice(x1,x2),
      _1392: x0 => x0.deviceMemory,
      _1393: x0 => x0.getBattery(),
      _1394: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1394(f,arguments.length,x0) }),
      _1395: () => globalThis.removeSplashFromWeb(),
      _1396: (x0,x1) => x0.appendChild(x1),
      _1397: (x0,x1) => x0.querySelector(x1),
      _1399: (x0,x1) => x0.matchMedia(x1),
      _1401: x0 => x0.pyodide,
      _1404: x0 => x0.webSocketEndpoint,
      _1405: x0 => x0.routeUrlStrategy,
      _1410: x0 => x0.assetsDir,
      _1411: () => globalThis.flet,
      _1412: Date.now,
      _1414: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1415: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1416: () => new Error().stack,
      _1417: () => typeof dartUseDateNowForTicks !== "undefined",
      _1418: () => 1000 * performance.now(),
      _1419: () => Date.now(),
      _1420: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1421: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1422: () => new WeakMap(),
      _1423: (map, o) => map.get(o),
      _1424: (map, o, v) => map.set(o, v),
      _1425: (exn) => exn.toString(),
      _1426: (exn) => exn.stack,
      _1427: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1428: x0 => new WeakRef(x0),
      _1429: x0 => x0.deref(),
      _1430: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1430(f,arguments.length,x0) }),
      _1431: x0 => new FinalizationRegistry(x0),
      _1432: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1434: (x0,x1) => x0.unregister(x1),
      _1436: () => globalThis.WeakRef,
      _1437: () => globalThis.FinalizationRegistry,
      _1440: s => JSON.stringify(s),
      _1441: s => printToConsole(s),
      _1442: (o, p, r) => o.replaceAll(p, () => r),
      _1443: (o, p, r) => o.replace(p, () => r),
      _1444: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1445: s => s.toUpperCase(),
      _1446: s => s.trim(),
      _1447: s => s.trimLeft(),
      _1448: s => s.trimRight(),
      _1449: (string, times) => string.repeat(times),
      _1450: Function.prototype.call.bind(String.prototype.indexOf),
      _1451: (s, p, i) => s.lastIndexOf(p, i),
      _1452: (string, token) => string.split(token),
      _1453: Object.is,
      _1456: (o, t) => typeof o === t,
      _1457: (o, c) => o instanceof c,
      _1458: o => Object.keys(o),
      _1461: (o, a) => o + a,
      _1488: x0 => new Array(x0),
      _1490: x0 => x0.length,
      _1492: (x0,x1) => x0[x1],
      _1493: (x0,x1,x2) => { x0[x1] = x2 },
      _1496: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1498: x0 => new Int8Array(x0),
      _1499: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1501: x0 => new Uint8ClampedArray(x0),
      _1503: x0 => new Int16Array(x0),
      _1505: x0 => new Uint16Array(x0),
      _1507: x0 => new Int32Array(x0),
      _1509: x0 => new Uint32Array(x0),
      _1511: x0 => new Float32Array(x0),
      _1513: x0 => new Float64Array(x0),
      _1537: x0 => x0.random(),
      _1538: (x0,x1) => x0.getRandomValues(x1),
      _1539: () => globalThis.crypto,
      _1540: () => globalThis.Math,
      _1553: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1554: (handle) => clearTimeout(handle),
      _1555: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1556: (handle) => clearInterval(handle),
      _1557: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1558: () => Date.now(),
      _1559: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1560: (x0,x1) => x0.exec(x1),
      _1561: (x0,x1) => x0.test(x1),
      _1562: x0 => x0.pop(),
      _1564: o => o === undefined,
      _1566: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1568: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1569: o => o instanceof RegExp,
      _1570: (l, r) => l === r,
      _1571: o => o,
      _1572: o => o,
      _1573: o => o,
      _1574: b => !!b,
      _1575: o => o.length,
      _1577: (o, i) => o[i],
      _1578: f => f.dartFunction,
      _1579: () => ({}),
      _1580: () => [],
      _1582: () => globalThis,
      _1583: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1584: (o, p) => p in o,
      _1585: (o, p) => o[p],
      _1586: (o, p, v) => o[p] = v,
      _1587: (o, m, a) => o[m].apply(o, a),
      _1589: o => String(o),
      _1590: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1591: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1591(f,arguments.length,x0) }),
      _1592: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1592(f,arguments.length,x0,x1) }),
      _1593: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1594: o => [o],
      _1595: (o0, o1) => [o0, o1],
      _1596: (o0, o1, o2) => [o0, o1, o2],
      _1597: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1598: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1599: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1600: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1601: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1602: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1603: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1604: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1605: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1606: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1607: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1608: x0 => new ArrayBuffer(x0),
      _1609: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1610: x0 => x0.input,
      _1611: x0 => x0.index,
      _1612: x0 => x0.groups,
      _1613: x0 => x0.flags,
      _1614: x0 => x0.multiline,
      _1615: x0 => x0.ignoreCase,
      _1616: x0 => x0.unicode,
      _1617: x0 => x0.dotAll,
      _1618: (x0,x1) => { x0.lastIndex = x1 },
      _1619: (o, p) => p in o,
      _1620: (o, p) => o[p],
      _1623: () => new XMLHttpRequest(),
      _1624: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1628: x0 => x0.send(),
      _1630: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1630(f,arguments.length,x0) }),
      _1631: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1631(f,arguments.length,x0) }),
      _1636: (x0,x1) => new WebSocket(x0,x1),
      _1637: (x0,x1) => x0.send(x1),
      _1638: (x0,x1,x2) => x0.close(x1,x2),
      _1640: x0 => x0.close(),
      _1643: () => new AbortController(),
      _1644: x0 => x0.abort(),
      _1645: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1646: (x0,x1) => globalThis.fetch(x0,x1),
      _1647: (x0,x1) => x0.get(x1),
      _1648: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1648(f,arguments.length,x0,x1,x2) }),
      _1649: (x0,x1) => x0.forEach(x1),
      _1650: x0 => x0.getReader(),
      _1651: x0 => x0.cancel(),
      _1652: x0 => x0.read(),
      _1653: (x0,x1) => x0.key(x1),
      _1654: o => o instanceof Array,
      _1655: (a, i) => a.push(i),
      _1656: (a, i) => a.splice(i, 1)[0],
      _1657: (a, i, v) => a.splice(i, 0, v),
      _1659: a => a.pop(),
      _1660: (a, i) => a.splice(i, 1),
      _1662: (a, s, e) => a.slice(s, e),
      _1664: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1665: a => a.length,
      _1666: (a, l) => a.length = l,
      _1667: (a, i) => a[i],
      _1668: (a, i, v) => a[i] = v,
      _1670: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1671: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1673: o => o instanceof Uint8Array,
      _1674: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1675: o => o instanceof Int8Array,
      _1676: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1677: o => o instanceof Uint8ClampedArray,
      _1678: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1679: o => o instanceof Uint16Array,
      _1680: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1681: o => o instanceof Int16Array,
      _1682: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1683: o => o instanceof Uint32Array,
      _1684: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1685: o => o instanceof Int32Array,
      _1686: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1688: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1689: o => o instanceof Float32Array,
      _1690: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1691: o => o instanceof Float64Array,
      _1692: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1693: (t, s) => t.set(s),
      _1694: l => new DataView(new ArrayBuffer(l)),
      _1695: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1696: o => o.byteLength,
      _1697: o => o.buffer,
      _1698: o => o.byteOffset,
      _1699: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1700: (b, o) => new DataView(b, o),
      _1701: (b, o, l) => new DataView(b, o, l),
      _1702: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1703: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1704: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1705: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1706: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1707: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1708: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1709: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1710: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1711: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1712: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1713: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1714: Function.prototype.call.bind(DataView.prototype.getBigUint64),
      _1716: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1717: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1718: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1719: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1720: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1721: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1722: Function.prototype.call.bind(Number.prototype.toString),
      _1723: Function.prototype.call.bind(BigInt.prototype.toString),
      _1724: Function.prototype.call.bind(Number.prototype.toString),
      _1725: (d, digits) => d.toFixed(digits),
      _1738: () => globalThis.document,
      _1739: () => globalThis.window,
      _1744: (x0,x1) => { x0.height = x1 },
      _1746: (x0,x1) => { x0.width = x1 },
      _1748: (x0,x1) => { x0.pointerEvents = x1 },
      _1751: x0 => x0.head,
      _1752: x0 => x0.classList,
      _1756: (x0,x1) => { x0.innerText = x1 },
      _1757: x0 => x0.style,
      _1759: x0 => x0.sheet,
      _1760: x0 => x0.src,
      _1761: (x0,x1) => { x0.src = x1 },
      _1762: x0 => x0.naturalWidth,
      _1763: x0 => x0.naturalHeight,
      _1770: x0 => x0.offsetX,
      _1771: x0 => x0.offsetY,
      _1772: x0 => x0.button,
      _1779: x0 => x0.status,
      _1780: (x0,x1) => { x0.responseType = x1 },
      _1782: x0 => x0.response,
      _1831: (x0,x1) => { x0.responseType = x1 },
      _1832: x0 => x0.response,
      _1892: (x0,x1) => { x0.draggable = x1 },
      _1908: x0 => x0.style,
      _2265: (x0,x1) => { x0.target = x1 },
      _2267: (x0,x1) => { x0.download = x1 },
      _2292: (x0,x1) => { x0.href = x1 },
      _2511: x0 => x0.error,
      _2513: (x0,x1) => { x0.src = x1 },
      _2518: (x0,x1) => { x0.crossOrigin = x1 },
      _2521: (x0,x1) => { x0.preload = x1 },
      _2525: x0 => x0.currentTime,
      _2526: (x0,x1) => { x0.currentTime = x1 },
      _2527: x0 => x0.duration,
      _2532: (x0,x1) => { x0.playbackRate = x1 },
      _2541: (x0,x1) => { x0.loop = x1 },
      _2562: x0 => x0.code,
      _2563: x0 => x0.message,
      _2834: (x0,x1) => { x0.accept = x1 },
      _2848: x0 => x0.files,
      _2874: (x0,x1) => { x0.multiple = x1 },
      _2892: (x0,x1) => { x0.type = x1 },
      _3141: (x0,x1) => { x0.src = x1 },
      _3143: (x0,x1) => { x0.type = x1 },
      _3147: (x0,x1) => { x0.async = x1 },
      _3161: (x0,x1) => { x0.charset = x1 },
      _3610: () => globalThis.window,
      _3670: x0 => x0.navigator,
      _3674: x0 => x0.screen,
      _3677: x0 => x0.innerHeight,
      _3681: x0 => x0.screenLeft,
      _3685: x0 => x0.outerHeight,
      _3933: x0 => x0.sessionStorage,
      _3934: x0 => x0.localStorage,
      _4035: x0 => x0.clipboard,
      _4043: x0 => x0.maxTouchPoints,
      _4050: x0 => x0.appCodeName,
      _4051: x0 => x0.appName,
      _4052: x0 => x0.appVersion,
      _4053: x0 => x0.platform,
      _4054: x0 => x0.product,
      _4055: x0 => x0.productSub,
      _4056: x0 => x0.userAgent,
      _4057: x0 => x0.vendor,
      _4058: x0 => x0.vendorSub,
      _4060: x0 => x0.language,
      _4061: x0 => x0.languages,
      _4062: x0 => x0.onLine,
      _4067: x0 => x0.hardwareConcurrency,
      _4107: x0 => x0.data,
      _4264: x0 => x0.length,
      _4481: x0 => x0.readyState,
      _4490: x0 => x0.protocol,
      _4494: (x0,x1) => { x0.binaryType = x1 },
      _4497: x0 => x0.code,
      _4498: x0 => x0.reason,
      _5648: x0 => x0.destination,
      _5652: x0 => x0.state,
      _5743: (x0,x1) => { x0.value = x1 },
      _5892: x0 => x0.gain,
      _6160: x0 => x0.type,
      _6201: x0 => x0.signal,
      _6262: x0 => x0.firstChild,
      _6273: () => globalThis.document,
      _6355: x0 => x0.body,
      _6357: x0 => x0.head,
      _6684: x0 => x0.id,
      _6685: (x0,x1) => { x0.id = x1 },
      _6712: x0 => x0.children,
      _8030: x0 => x0.value,
      _8032: x0 => x0.done,
      _8211: x0 => x0.size,
      _8212: x0 => x0.type,
      _8215: (x0,x1) => { x0.type = x1 },
      _8218: x0 => x0.name,
      _8224: x0 => x0.length,
      _8229: x0 => x0.result,
      _8726: x0 => x0.url,
      _8728: x0 => x0.status,
      _8730: x0 => x0.statusText,
      _8731: x0 => x0.headers,
      _8732: x0 => x0.body,
      _8807: x0 => x0.types,
      _9011: x0 => x0.matches,
      _9024: x0 => x0.width,
      _9025: x0 => x0.height,
      _11135: (x0,x1) => { x0.display = x1 },
      _12280: x0 => x0.charging,
      _12283: x0 => x0.level,
      _12285: (x0,x1) => { x0.onchargingchange = x1 },
      _12357: x0 => x0.name,
      _12358: x0 => x0.message,
      _13100: x0 => x0.x,
      _13101: x0 => x0.y,
      _13102: x0 => x0.z,
      _13103: (x0,x1) => { x0.onreading = x1 },
      _13104: (x0,x1) => { x0.onerror = x1 },
      _13105: x0 => x0.x,
      _13106: x0 => x0.y,
      _13107: x0 => x0.z,
      _13108: (x0,x1) => { x0.onreading = x1 },
      _13109: (x0,x1) => { x0.onerror = x1 },
      _13110: x0 => x0.x,
      _13111: x0 => x0.y,
      _13112: x0 => x0.z,
      _13113: (x0,x1) => { x0.onreading = x1 },
      _13114: (x0,x1) => { x0.onerror = x1 },
      _13115: x0 => x0.x,
      _13116: x0 => x0.y,
      _13117: x0 => x0.z,
      _13118: (x0,x1) => { x0.onreading = x1 },
      _13119: (x0,x1) => { x0.onerror = x1 },
      _13120: x0 => x0.error,
      _13121: x0 => x0.name,
      _13122: x0 => x0.message,
      _13127: x0 => globalThis.Wakelock.toggle(x0),
      _13128: () => globalThis.Wakelock.enabled(),

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
